name: publish-nuget-packages

on: 
  release:
    types: [published, prereleased]

jobs: 
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - run: |
        echo "Github ref is ${GITHUB_REF}"
        arrTag=(${GITHUB_REF//\// })
        VERSION="${arrTag[2]}"
        echo "Version: $VERSION"
        dotnet pack src/PromQL.Parser --include-symbols -c "Release" -p:Version=$VERSION  --output "build/"
        dotnet nuget push "build/PromQL.Parser.*.symbols.nupkg" -k ${{ secrets.NUGET_API_KEY }} -s "https://api.nuget.org/v3/index.json" --no-symbols
